# Site settings
title: 码道人的博客
SEOTitle: 码道人 | Joven | Mainxx | 键盘里的鼠标
header-img: img/home-bg.jpg
email: joven@mainxx.com
description: "关于全栈的进修之路，在思想升华的路上。 | 我使用过的ID：Joven,Mainxx,键盘里的鼠标,码道人 | 这里是 @码道人 的个人博客，一起把知识消化，永无止境追求着。。"
keyword: "Joven, Mainxx, 码道人, 钟钊文的博客, , @mainxx, Joven Blog, 博客, 个人网站, .net Core, ABP, DDD, .net, 互联网, 架构,"
url: "https://joven.site"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

collections:
  ASPNET.Zero:
    output: true
    permalink: /:collection/:name
  Quartz.NET:
    output: true
    permalink: /:collection/:name
# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
#weibo_username:     mainxx
zhihu_username:     joven-41
github_username:    mainxx
cnblogs_username:   mainxx
gitee_username:     mainxx
#twitter_username:   mainxx
#facebook_username:  mainxx
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: mainxx

# Netease settings
netease_comment: false

# Gitment settings
# gitment_enabled 是否启用Gitment
# gitment_owner: '你的 GitHub ID',
# gitment_repo: '存储评论的 repo',
# gitment_client_id: '你的 client ID',
# gitment_client_secret: '你的 client secret',
gitment_enabled: true
gitment_owner: mainxx
gitment_repo: mainxx.github.io
gitment_client_id: 431cf8bd9e44b0420dd6
gitment_client_secret: bc5fc1abdd263e4f077855e9d69f3eebcff1200c

# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
#ga_track_id: 'UA-xxxxxx-xx'            # Format: UA-xxxxxx-xx
#ga_domain: joven.site



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "敲下代码，思考人生，<br>知识消化是一种探索，它永无止境。"
sidebar-avatar: /img/avatar-joven2.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Annie2x",
        href: "http://annie2x.com/"
    }
    {
        title: "危杨益的博客园",
        href: "https://www.cnblogs.com/yy690486439"
    }
]
